apiVersion: apps/v1
kind: Deployment
metadata:
  name: greet-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greet-app
  template:
    metadata:
      labels:
        app: greet-app
    spec:
      containers:
        - name: greet-container
          image: greet-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081 