apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: hello-app
          env:
            - name: ENV
              value: "dev"
            - name: LOG_LEVEL
              value: "debug" 