apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patches:
  - path: hello-patch.yaml
  - path: greet-patch.yaml
  - path: service-config-patch.yaml

images:
  - name: hello-app
    newName: hello-app
    newTag: "dev"
  - name: greet-app
    newName: greet-app
    newTag: "dev" 